- name: variables from files
  hosts: local
  connection: local
  vars_files:
    - course.yaml
  tasks:
    - name: print course information
      ansible.builtin.debug:
        msg: "Hello, this is {{ COURSE }} and it lasts for {{ DURATION }}. And Instructor: {{ INSTRUCTOR }}"
        