- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
    - name: username
      prompt: "Enter your username"
      private: true
    
    - name: password
      prompt: "Enter your password"
      private: true
  tasks:
    - name: Print user credentials
      ansible.builtin.debug:
        msg: "Username: {{ username }}, Password: {{ password }}"