- name: loops
  hosts: local
  connection: local
  tasks:
    - name: Print Names
      ansible.builtin.debug:
        msg: "{{ item }}"  # Here item is the reserved keyword for loop iteration
      loop:
      - "Siva"
      - "Siva 2"
      - "Siva 3"


- name: Install Packages
  hosts: frontend
  become: yes
  tasks:
    - name: Installing Packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: installed
      loop:
      - nginx
      - mysql
      - zip  