- name: Converting String into List
  hosts: local
  connection: local
  vars:
    persons: "Albert, Bob, Charlie" # String of names separated by commas
  tasks: 
    - name: Check undefined variables
      ansible.builtin.debug:
        msg: "Hello, {{ person | default('World') }}!"  # Default to 'World' if 'person' is undefined"
  
    - name: Print Names
      ansible.builtin.debug:
        msg: "Hello, {{ persons }}!" # Print the string of names

    - name: Convert String to List
      ansible.builtin.debug:
        msg: "Hello, {{ persons.split(',') }}!"

    - name: Print each name from the List
      ansible.builtin.debug:
        msg: "Hello, {{ item }}!"  # Print each name from the list
      loop: "{{ persons.split(',') }}" # Loop through the list created by splitting the string

    - name: Convert Map into List
      vars:
        course:
          name: "Ansible"
          duration: "2 months"
          trainer: "Siva"
      ansible.builtin.debug:
        msg: "Course Details: {{ course | dict2items }}" # Convert map to list of items
        # dict2items converts a dictionary into a list of dictionaries with 'key' and 'value' keys

    - name: Convert List into Map
      vars:
        course:
          - { key: 'name', value: 'Ansible' }
          - { key: 'duration', value: '2 months' }
          - { key: 'trainer', value: 'Siva' }
      ansible.builtin.debug:
        msg: "Course Details: {{ course | items2dict }}" # Convert list of items back to a dictionary
        # items2dict converts a list of dictionaries with 'key' and 'value' keys into a single dictionary

    - name: Convert to String to Uppercase
      vars: 
        name: "Test Name" 
      ansible.builtin.debug:
        msg: "Hello, {{ name | upper}}!" # Convert string to uppercase

    - name: Check if the IP Address is valid
      ansible.builtin.debug:
        msg: "IP Address is: {{ ip_address | ansible.utils.ipaddr }} "
      loop:
        - { ip_address: "300.345.286.210" } # Invalid IP address
        - { ip_address: "129.22.130.249" } # Valid IP address
